
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { TrendingUp, TrendingDown, DollarSign, Eye, MousePointer, Target } from "lucide-react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';

const dummyData = [
  { date: 'Jun 1', spend: 1200, conversions: 24, clicks: 480, impressions: 12000 },
  { date: 'Jun 7', spend: 1350, conversions: 28, clicks: 520, impressions: 13500 },
  { date: 'Jun 14', spend: 1180, conversions: 22, clicks: 450, impressions: 11800 },
  { date: 'Jun 21', spend: 1420, conversions: 32, clicks: 580, impressions: 14200 },
  { date: 'Jun 28', spend: 1550, conversions: 38, clicks: 620, impressions: 15500 },
];

const Report = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [showCheckout, setShowCheckout] = useState(false);

  const totalSpend = dummyData.reduce((sum, item) => sum + item.spend, 0);
  const totalConversions = dummyData.reduce((sum, item) => sum + item.conversions, 0);
  const totalClicks = dummyData.reduce((sum, item) => sum + item.clicks, 0);
  const totalImpressions = dummyData.reduce((sum, item) => sum + item.impressions, 0);
  
  const avgCTR = ((totalClicks / totalImpressions) * 100).toFixed(2);
  const avgCPC = (totalSpend / totalClicks).toFixed(2);
  const avgCPA = (totalSpend / totalConversions).toFixed(2);

  const handleGetReport = () => {
    // Show settings reminder popup for 3 seconds
    setShowCheckout(true);
    setTimeout(() => setShowCheckout(false), 3000);
    
    // Navigate to checkout after a short delay
    setTimeout(() => navigate('/checkout'), 1000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      {/* Settings Reminder Popup */}
      {showCheckout && (
        <div className="fixed top-20 left-1/2 transform -translate-x-1/2 z-50 bg-blue-600 text-white px-6 py-3 rounded-lg shadow-lg animate-in fade-in slide-in-from-top-2">
          <p className="text-sm">💡 Make sure your ad accounts and KPI preferences are updated in Settings!</p>
        </div>
      )}

      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            Your Ad Performance Report
          </h1>
          <p className="text-lg text-gray-600">
            Welcome back, {user?.user_metadata?.full_name || user?.email}! Here's how your campaigns performed.
          </p>
          <p className="text-sm text-gray-500 mt-2">June 2025 • Generated by AdPulse</p>
        </div>

        {/* Executive Summary */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5 text-green-600" />
              Executive Summary
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="text-center">
                <div className="text-2xl font-bold text-gray-900">${totalSpend.toLocaleString()}</div>
                <div className="text-sm text-gray-600">Total Spend</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">{totalImpressions.toLocaleString()}</div>
                <div className="text-sm text-gray-600">Impressions</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-green-600">{totalClicks.toLocaleString()}</div>
                <div className="text-sm text-gray-600">Clicks</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-purple-600">{totalConversions}</div>
                <div className="text-sm text-gray-600">Conversions</div>
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6 pt-6 border-t">
              <div className="text-center">
                <div className="text-lg font-semibold text-gray-900">{avgCTR}%</div>
                <div className="text-sm text-gray-600">Avg CTR</div>
              </div>
              <div className="text-center">
                <div className="text-lg font-semibold text-gray-900">${avgCPC}</div>
                <div className="text-sm text-gray-600">Avg CPC</div>
              </div>
              <div className="text-center">
                <div className="text-lg font-semibold text-gray-900">${avgCPA}</div>
                <div className="text-sm text-gray-600">Avg CPA</div>
              </div>
            </div>
            <div className="mt-6 p-4 bg-green-50 rounded-lg">
              <div className="flex items-center gap-2 text-green-800">
                <TrendingUp className="h-4 w-4" />
                <span className="font-semibold">Key Insight:</span>
              </div>
              <p className="text-green-700 mt-1">Your CTR improved 12% over last month, with Meta Ads being your top-performing platform.</p>
            </div>
          </CardContent>
        </Card>

        {/* Performance Charts */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <Card>
            <CardHeader>
              <CardTitle>Spend vs Conversions</CardTitle>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={250}>
                <LineChart data={dummyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Line type="monotone" dataKey="spend" stroke="#3b82f6" strokeWidth={2} />
                  <Line type="monotone" dataKey="conversions" stroke="#10b981" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Clicks vs Impressions</CardTitle>
            </CardHeader>
            <CardContent>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={dummyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="clicks" fill="#8b5cf6" />
                  <Bar dataKey="impressions" fill="#06b6d4" opacity={0.6} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </div>

        {/* AI Recommendations */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Target className="h-5 w-5 text-blue-600" />
              AI-Powered Recommendations
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 bg-blue-50 rounded-lg border-l-4 border-blue-500">
              <p className="font-semibold text-blue-900">Budget Reallocation</p>
              <p className="text-blue-800">Move 20% of budget from low-CTR audience segments to high-performing lookalike audiences.</p>
            </div>
            <div className="p-4 bg-red-50 rounded-lg border-l-4 border-red-500">
              <p className="font-semibold text-red-900">Campaign Alert</p>
              <p className="text-red-800">Pause "Summer Sale Campaign A" - cost increased 35% with declining ROAS over past week.</p>
            </div>
            <div className="p-4 bg-green-50 rounded-lg border-l-4 border-green-500">
              <p className="font-semibold text-green-900">Opportunity</p>
              <p className="text-green-800">Increase bids on California lookalike audiences - performing 18% better than average.</p>
            </div>
          </CardContent>
        </Card>

        {/* Audience Breakdown */}
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Audience & Demographics</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <h4 className="font-semibold mb-3">Platform Split</h4>
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span>Google Ads</span>
                    <span className="font-semibold">58%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Meta Ads</span>
                    <span className="font-semibold">42%</span>
                  </div>
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Top Age Groups</h4>
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span>25-34</span>
                    <span className="font-semibold">38%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>35-44</span>
                    <span className="font-semibold">31%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>18-24</span>
                    <span className="font-semibold">19%</span>
                  </div>
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Device Breakdown</h4>
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span>Mobile</span>
                    <span className="font-semibold">64%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Desktop</span>
                    <span className="font-semibold">28%</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Tablet</span>
                    <span className="font-semibold">8%</span>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Campaign Breakdown Table - This starts to fade */}
        <div className="relative">
          <Card className="mb-8">
            <CardHeader>
              <CardTitle>Campaign Performance</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left py-2">Campaign</th>
                      <th className="text-right py-2">Spend</th>
                      <th className="text-right py-2">Impressions</th>
                      <th className="text-right py-2">CTR</th>
                      <th className="text-right py-2">Conversions</th>
                      <th className="text-right py-2">ROAS</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b">
                      <td className="py-2">Summer Sale - Google</td>
                      <td className="text-right">$2,340</td>
                      <td className="text-right">45,600</td>
                      <td className="text-right">2.8%</td>
                      <td className="text-right">68</td>
                      <td className="text-right">3.2x</td>
                    </tr>
                    <tr className="border-b">
                      <td className="py-2">Brand Awareness - Meta</td>
                      <td className="text-right">$1,890</td>
                      <td className="text-right">38,200</td>
                      <td className="text-right">3.1%</td>
                      <td className="text-right">52</td>
                      <td className="text-right">2.9x</td>
                    </tr>
                    <tr className="border-b">
                      <td className="py-2">Retargeting - Google</td>
                      <td className="text-right">$1,245</td>
                      <td className="text-right">18,900</td>
                      <td className="text-right">4.2%</td>
                      <td className="text-right">38</td>
                      <td className="text-right">4.1x</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          {/* Fade overlay */}
          <div className="absolute inset-0 bg-gradient-to-t from-white via-white/80 to-transparent pointer-events-none" 
               style={{ top: '60%' }}></div>
        </div>

        {/* Get My Report Button */}
        <div className="text-center py-12 relative z-10">
          <div className="bg-white/90 backdrop-blur-sm rounded-2xl p-8 max-w-md mx-auto shadow-xl border">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Want Your Real Report?</h3>
            <p className="text-gray-600 mb-6">
              Connect your ad accounts and get a personalized analysis of your actual campaign data with AI-powered recommendations.
            </p>
            <Button 
              onClick={handleGetReport}
              size="lg"
              className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-3 text-lg"
            >
              Get My Report - $5 📊
            </Button>
            <p className="text-xs text-gray-500 mt-3">
              Professional PDF report delivered to your email
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Report;
