// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkhldflxtvrsnidxbqzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraGxkZmx4dHZyc25pZHhicXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzI1MzksImV4cCI6MjA2NjY0ODUzOX0.cMq7vd_0_CFBSeesjbmCNF40OcfWFOHrm4V38PHmv8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);